export const mockSuppliers = {
    Galychyna: {
        rating: 1.0,
        price: '59.99',
        conditions: ['День в день', 'Мін. замовлення $900'],
        selected: false,
        unit: '1kg',
    },
    Mlekovita: {
        rating: 1.0,
        price: '59.99',
        conditions: ['День в день', 'Мін. замовлення $900'],
        selected: false,
        unit: '1kg',
    },
    Alpha: {
        rating: 1.0,
        price: '59.99',
        conditions: ['День в день', 'Мін. замовлення $900'],
        selected: false,
        unit: '1kg',
    },
    Bravo: {
        rating: 1.0,
        price: '59.99',
        conditions: ['День в день', 'Мін. замовлення $900'],
        selected: false,
        unit: '1kg',
    },
    Charlie: {
        rating: 1.0,
        price: '59.99',
        conditions: ['День в день', 'Мін. замовлення $900'],
        selected: false,
        unit: '1kg',
    },
    Delta: {
        rating: 1.0,
        price: '59.99',
        conditions: ['День в день', 'Мін. замовлення $900'],
        selected: false,
        unit: '1kg',
    },
    Echo: {
        rating: 1.0,
        price: '59.99',
        conditions: ['День в день', 'Мін. замовлення $900'],
        selected: false,
        unit: '1kg',
    },
};
