export const profileTypes = {
    // Sync
    FILL_PROFILE: 'FILL_PROFILE',
    CLEAR_PROFILE: 'CLEAR_PROFILE',
    FILL_REFERRAL_DATA: 'FILL_REFERRAL_DATA',
    UPDATE_NICKNAME: 'UPDATE_NICKNAME',
    UPDATE_EMAIL: 'UPDATE_EMAIL',
    UPDATE_CART: 'UPDATE_CART',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
    ADD_ITEM_TO_FAVORITES: 'ADD_ITEM_TO_FAVORITES',
    REMOVE_ITEM_FROM_FAVORITES: 'REMOVE_ITEM_FROM_FAVORITES',
    REPEAT_LAST_ORDER: 'REPEAT_LAST_ORDER',

    // Async
    GET_REFERRAL_DATA_ASYNC: 'GET_REFERRAL_DATA_ASYNC',
    UPDATE_EMAIL_ASYNC: 'UPDATE_EMAIL_ASYNC',
    ADD_ITEM_TO_CART_ASYNC: 'ADD_ITEM_TO_CART_ASYNC',
    REMOVE_ITEM_FROM_CART_ASYNC: 'REMOVE_ITEM_FROM_CART_ASYNC',
    ADD_ITEM_TO_FAVORITES_ASYNC: 'ADD_ITEM_TO_FAVORITES_ASYNC',
    REMOVE_ITEM_FROM_FAVORITES_ASYNC: 'REMOVE_ITEM_FROM_FAVORITES_ASYNC',
    GET_USER_DATA_ASYNC: 'GET_USER_DATA_ASYNC',
};
