export const profileTypes = {
    //Sync
    FILL_PROFILE: 'FILL_PROFILE',
    CLEAR_PROFILE: 'CLEAR_PROFILE',
    OPEN_TUTORIAL: 'OPEN_TUTORIAL',
    CLOSE_TUTORIAL: 'CLOSE_TUTORIAL',
    FILL_REFERRAL_DATA: 'FILL_REFERRAL_DATA',
    UPDATE_NICKNAME: 'UPDATE_NICKNAME',
    UPDATE_EMAIL: 'UPDATE_EMAIL',
    FILL_WEEKLY_CHALLENGE_DATA: 'FILL_WEEKLY_CHALLENGE_DATA',
    FILL_DAILY_CHALLENGE_DATA: 'FILL_DAILY_CHALLENGE_DATA',
    FILL_DAILY_REWARD_DATA: 'FILL_DAILY_REWARD_DATA',

    //Async
    GET_REFERRAL_DATA_ASYNC: 'GET_REFERRAL_DATA_ASYNC',
    UPDATE_NICKNAME_ASYNC: 'UPDATE_NICKNAME_ASYNC',
    UPDATE_EMAIL_ASYNC: 'UPDATE_EMAIL_ASYNC',
    GET_WEEKLY_CHALLENGE_DATA_ASYNC: 'GET_WEEKLY_CHALLENGE_DATA_ASYNC',
    SET_WEEKLY_CHALLENGE_GAME_ASYNC: 'SET_WEEKLY_CHALLENGE_GAME_ASYNC',
    GET_DAILY_CHALLENGE_DATA_ASYNC: 'GET_DAILY_CHALLENGE_DATA_ASYNC',
    GET_DAILY_REWARD_DATA_ASYNC: 'GET_DAILY_REWARD_DATA_ASYNC',
    SET_LANGUAGE_ASYNC: 'SET_LANGUAGE_ASYNC',
};
