export const profileTypes = {
    // Sync
    FILL_PROFILE: 'FILL_PROFILE',
    CLEAR_PROFILE: 'CLEAR_PROFILE',
    FILL_REFERRAL_DATA: 'FILL_REFERRAL_DATA',
    UPDATE_NICKNAME: 'UPDATE_NICKNAME',
    UPDATE_EMAIL: 'UPDATE_EMAIL',
    UPDATE_CART: 'UPDATE_CART',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
    ADD_ITEM_TO_FAVORITES: 'ADD_ITEM_TO_FAVORITES',
    REMOVE_ITEM_FROM_FAVORITES: 'REMOVE_ITEM_FROM_FAVORITES',
    REPEAT_LAST_ORDER: 'REPEAT_LAST_ORDER',
    FILL_SUPPLIER_PREVIEW: 'FILL_SUPPLIER_PREVIEW',
    UPDATE_PREVIEW_DATA: 'UPDATE_PREVIEW_DATA',

    // Async
    GET_REFERRAL_DATA_ASYNC: 'GET_REFERRAL_DATA_ASYNC',
    UPDATE_EMAIL_ASYNC: 'UPDATE_EMAIL_ASYNC',
    ADD_ITEM_TO_CART_ASYNC: 'ADD_ITEM_TO_CART_ASYNC',
    REMOVE_ITEM_FROM_CART_ASYNC: 'REMOVE_ITEM_FROM_CART_ASYNC',
    ADD_ITEM_TO_FAVORITES_ASYNC: 'ADD_ITEM_TO_FAVORITES_ASYNC',
    REMOVE_ITEM_FROM_FAVORITES_ASYNC: 'REMOVE_ITEM_FROM_FAVORITES_ASYNC',
    GET_USER_DATA_ASYNC: 'GET_USER_DATA_ASYNC',
    UPLOAD_SUPPLIER_EXCEL_TABLE_ASYNC: 'UPLOAD_SUPPLIER_EXCEL_TABLE_ASYNC',
    REMOVE_ITEM_FROM_PREVIEW_ASYNC: 'REMOVE_ITEM_FROM_PREVIEW_ASYNC',
    UPDATE_ITEM_FROM_PREVIEW_ASYNC: 'UPDATE_ITEM_FROM_PREVIEW_ASYNC',
    UPDATE_SUPPLIER_ITEMS_ASYNC: 'UPDATE_SUPPLIER_ITEMS_ASYNC',
    ADD_NEW_SUPPLIER_ITEM_ASYNC: 'ADD_NEW_SUPPLIER_ITEM_ASYNC',
};
