export const authTypes = {
    AUTHENTICATE_USER: 'AUTHENTICATE_USER',
    OPEN_LOGIN_CODE_CONFIRMATION: 'OPEN_LOGIN_CODE_CONFIRMATION',
    CLOSE_LOGIN_CODE_CONFIRMATION: 'CLOSE_LOGIN_CODE_CONFIRMATION',
    SIGN_OUT: 'SIGN_OUT',

    //Async
    GET_AUTH_CONFIRMATION_CODE_ASYNC: 'GET_AUTH_CONFIRMATION_CODE_ASYNC',
    SEND_CONFIRMATION_CODE_ASYNC: 'SEND_CONFIRMATION_CODE_ASYNC',
};
