export const authTypes = {
    AUTHENTICATE_USER: 'AUTHENTICATE_USER',
    OPEN_CODE_CONFIRMATION: 'OPEN_CODE_CONFIRMATION',
    CLOSE_CODE_CONFIRMATION: 'CLOSE_CODE_CONFIRMATION',
    SIGN_OUT: 'SIGN_OUT',
    SET_AUTH_DATA: 'SET_AUTH_DATA',
    FILL_GOOGLE_MAPS_KEY: 'FILL_GOOGLE_MAPS_KEY',

    //Async
    GET_AUTH_CONFIRMATION_CODE_ASYNC: 'GET_AUTH_CONFIRMATION_CODE_ASYNC',
    SEND_CONFIRMATION_CODE_ASYNC: 'SEND_CONFIRMATION_CODE_ASYNC',
    GET_SIGNUP_CONFIRMATION_CODE_ASYNC: 'GET_SIGNUP_CONFIRMATION_CODE_ASYNC',
    SEND_SIGNUP_DATA_ASYNC: 'SEND_SIGNUP_DATA_ASYNC',
    GET_GOOGLE_MAPS_KEY_ASYNC: 'GET_GOOGLE_MAPS_KEY_ASYNC',
};
