export const authTypes = {
    AUTHENTICATE_USER: 'AUTHENTICATE_USER',
    OPEN_CODE_CONFIRMATION: 'OPEN_CODE_CONFIRMATION',
    CLOSE_CODE_CONFIRMATION: 'CLOSE_CODE_CONFIRMATION',
    LOG_OUT: 'LOG_OUT',
    SET_AUTH_DATA: 'SET_AUTH_DATA',
    SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
    CLEAR_ACCESS_TOKEN: 'CLEAR_ACCESS_TOKEN',

    // Async
    GET_SIGNIN_CONFIRMATION_CODE_ASYNC: 'GET_SIGNIN_CONFIRMATION_CODE_ASYNC',
    SIGNIN_ASYNC: 'SIGNIN_ASYNC',
    GET_SIGNUP_CONFIRMATION_CODE_ASYNC: 'GET_SIGNUP_CONFIRMATION_CODE_ASYNC',
    SEND_SIGNUP_DATA_ASYNC: 'SEND_SIGNUP_DATA_ASYNC',
    LOG_OUT_ASYNC: 'LOG_OUT_ASYNC',
};
