export const types = {
    // Spinner
    START_FETCHING: 'START_FETCHING',
    STOP_FETCHING: 'STOP_FETCHING',

    // Routing
    REDIRECT: 'REDIRECT',

    // Cart
    SHOW_CART: 'SHOW_CART',
    HIDE_CART: 'HIDE_CART',

    // Overlays
    SHOW_LOGIN_OVERLAY: 'SHOW_LOGIN_OVERLAY',
    SHOW_SIGNUP_OVERLAY: 'SHOW_SIGNUP_OVERLAY',
    SHOW_CODE_OVERLAY: 'SHOW_CODE_OVERLAY',
    HIDE_LOGIN_OVERLAY: 'HIDE_LOGIN_OVERLAY',
    HIDE_SIGNUP_OVERLAY: 'HIDE_SIGNUP_OVERLAY',
    HIDE_CODE_OVERLAY: 'HIDE_CODE_OVERLAY',
    HIDE_ALL_OVERLAYS: 'HIDE_ALL_OVERLAYS',

    // Errors
    EMIT_ERROR: 'EMIT_ERROR',
};
