export const types = {
    // Spinner
    START_FETCHING: 'START_FETCHING',
    STOP_FETCHING: 'STOP_FETCHING',

    // Routing
    REDIRECT: 'REDIRECT',
    SET_BACK_BUTTON_PATH: 'SET_BACK_BUTTON_PATH',

    // Market stuff
    SHOW_CART: 'SHOW_CART',
    SHOW_CART_ICON: 'SHOW_CART_ICON',
    HIDE_CART: 'HIDE_CART',
    HIDE_CART_ICON: 'HIDE_CART_ICON',
    SET_ORDER_PLACED_STATE: 'SET_ORDER_PLACED_STATE',
    SET_ORDER_ERROR_STATE: 'SET_ORDER_ERROR_STATE',

    // Show overlays
    SHOW_MARKET_FILTERS: 'SHOW_MARKET_FILTERS',
    SHOW_ORDERS_FILTERS: 'SHOW_ORDERS_FILTERS',
    SHOW_LOGIN_OVERLAY: 'SHOW_LOGIN_OVERLAY',
    SHOW_SIGNUP_OVERLAY: 'SHOW_SIGNUP_OVERLAY',
    SHOW_CODE_OVERLAY: 'SHOW_CODE_OVERLAY',
    SHOW_SEARCH_OVERLAY: 'SHOW_SEARCH_OVERLAY',
    SHOW_NEW_LOCATION_OVERLAY: 'SHOW_NEW_LOCATION_OVERLAY',
    SHOW_NEW_LIST_ITEM_OVERLAY: 'SHOW_NEW_LIST_ITEM_OVERLAY',
    SHOW_SUPPLIER_UPLOAD_OVERLAY: 'SHOW_SUPPLIER_UPLOAD_OVERLAY',

    // Hide overlays
    HIDE_MARKET_FILTERS: 'HIDE_MARKET_FILTERS',
    HIDE_ORDERS_FILTERS: 'HIDE_ORDERS_FILTERS',
    HIDE_LOGIN_OVERLAY: 'HIDE_LOGIN_OVERLAY',
    HIDE_SIGNUP_OVERLAY: 'HIDE_SIGNUP_OVERLAY',
    HIDE_CODE_OVERLAY: 'HIDE_CODE_OVERLAY',
    HIDE_SEARCH_OVERLAY: 'HIDE_SEARCH_OVERLAY',
    HIDE_ALL_OVERLAYS: 'HIDE_ALL_OVERLAYS',
    HIDE_NEW_LOCATION_OVERLAY: 'HIDE_NEW_LOCATION_OVERLAY',
    HIDE_NEW_LIST_ITEM_OVERLAY: 'HIDE_NEW_LIST_ITEM_OVERLAY',
    HIDE_SUPPLIER_UPLOAD_OVERLAY: 'HIDE_SUPPLIER_UPLOAD_OVERLAY',

    // Errors
    EMIT_ERROR: 'EMIT_ERROR',

    // TEMP
    WRITE_LOG: 'WRITE_LOG',
};
