export const marketTypes = {
    // Sync
    FILL_MARKET_CATEGORIES: 'FILL_MARKET_CATEGORIES',
    FILL_MARKET_CATEGORY_DATA: 'FILL_MARKET_CATEGORY_DATA',
    FILL_MARKET_SUBCATEGORY_DATA: 'FILL_MARKET_SUBCATEGORY_DATA',
    FILL_PRODUCT_DATA: 'FILL_PRODUCT_DATA',
    CLEAR_PRODUCT_DATA: 'CLEAR_PRODUCT_DATA',
    FILL_ORDER_DATA: 'FILL_ORDER_DATA',
    CLEAR_ORDER_DATA: 'CLEAR_ORDER_DATA',

    // Async
    GET_MARKET_CATEGORIES_ASYNC: 'GET_MARKET_CATEGORIES_ASYNC',
    GET_MARKET_CATEGORY_DATA_ASYNC: 'GET_MARKET_CATEGORY_DATA_ASYNC',
    GET_MARKET_SUBCATEGORY_DATA_ASYNC: 'GET_MARKET_SUBCATEGORY_DATA_ASYNC',
    GET_PRODUCT_DATA_ASYNC: 'GET_PRODUCT_DATA_ASYNC',
    CREATE_NEW_ORDER_ASYNC: 'CREATE_NEW_ORDER_ASYNC',
    GET_ORDER_DATA_ASYNC: 'GET_ORDER_DATA_ASYNC',
};
