export const marketTypes = {
    // Sync
    FILL_MARKET_CATEGORIES: 'FILL_MARKET_CATEGORIES',
    FILL_MARKET_CATEGORY_DATA: 'FILL_MARKET_CATEGORY_DATA',
    FILL_MARKET_SUBCATEGORY_DATA: 'FILL_MARKET_SUBCATEGORY_DATA',

    // Async
    GET_MARKET_CATEGORIES_ASYNC: 'GET_MARKET_CATEGORIES_ASYNC',
    GET_MARKET_CATEGORY_DATA_ASYNC: 'GET_MARKET_CATEGORY_DATA_ASYNC',
    GET_MARKET_SUBCATEGORY_DATA_ASYNC: 'GET_MARKET_SUBCATEGORY_DATA_ASYNC',
};
